### ISSUE TITLE
Move package to JuliaMath

### ISSUE THREAD

**Issue by ViralBShah** [JuliaMath/Cubature.jl#48]
@stevengj Do you think it is a good idea to move this project into JuliaMath? The code itself seems to require little to no maintenance, but putting it in the JuliaMath org might allow people to contribute to package maintenance such as #47.

**Comment by stevengj** [comment]
Sure, I have no problem with that.  Probably the HCubature.jl package too.

**Comment by stevengj** [comment]
Done.
