### ISSUE TITLE
Access to number of function evaluations

### ISSUE THREAD

**Issue by jwharington** [JuliaMath/Cubature.jl#55]
In order to assess the sampling efficiency of cubature methods, I'd like to be able to retrieve the number of evaluations used by the cubature code.  I can see it is possible to set the maximum number of evaluations, but this doesn't help.

**Comment by stevengj** [comment]
Just increment a global counter in your integrand.

**Comment by stevengj** [comment]
e.g.
```jl
let counter = 0
    @show hquadrature(x -> (counter += 1; x^3), 0,1)
    @show counter
end
```

**Comment by jwharington** [comment]
Many thanks!
