### ISSUE TITLE
Very slow for one-dimensional integral

### ISSUE THREAD

**Issue by urbainvaes** [JuliaMath/Cubature.jl#63]
Hi,

I noticed that `hquadrature` sometimes does not work. For example, the command

```julia
hquadrature(sin, -5,  5)
```

does not terminate. Is this a known issue? Strangely, the command works well if `maxevals` is provided.

**Comment by mzaffalon** [comment]
Related to https://github.com/JuliaMath/Cubature.jl/issues/34.

**Comment by stevengj** [comment]
As explained in the manual:

> More precisely, the integration will terminate when either the relative- or the absolute-error tolerances are met. abstol defaults to 0, which means that it is ignored, but it can be useful to specify an absoute error tolerance for integrands that may integrate to zero (or nearly zero) because of large cancellations, in which case the problem is ill-conditioned and a small relative error tolerance may be unachievable.

**Comment by urbainvaes** [comment]
Ah, all right! Thank you very much!
