### ISSUE TITLE
memory leaks in hcubature.c ?

### ISSUE THREAD

**Issue by ntessore** [JuliaMath/Cubature.jl#7]
I was running `hcubature_v` many, _many_ times in a row without theoretically allocating any new space, and it ended up filling 32 GB of RAM. I am not sure whether this is a cubature thing or a Julia thing (I'm still testing), but it seems that replacing the zero-resize in

``` c
static void heap_free(heap *h)
{
     h->n = 0;
     heap_resize(h, 0);
     h->fdim = 0;
     free(h->ee);
}
```

with an explicit free

``` c
static void heap_free(heap *h)
{
     h->n = 0;
     h->nalloc = 0;
     free(h->items);
     h->items = NULL;
     h->fdim = 0;
     free(h->ee);
}
```

fixes at least a large part of the memory issue.

I'm on Mac OS X Yosemite and checked that the same behaviour occurs with your provided library and with a self-built one.

**Comment by ChrisRackauckas** [comment]
Hey,
  I am getting massive amounts of memory usage as well with hcubature_v. I am running this on Windows. I don't know if it's a memory leak, but the memory usage ramps up to over 60Gb on a large problem, while the non-vectorized version is fine. How does Cubature choose the size of the vectors?

**Comment by stevengj** [comment]
@ChrisRackauckas, the `hcubature_v` routine maximizes parallelism, so it allocates memory for as many subregions as can be evaluated simultaneously.   At high resolutions or in high dimensions, this can be quite large.

One possible refinement would be to allow an upper bound on the parallelism, to prevent it from trying to evaluate too many regions at once.

**Comment by ChrisRackauckas** [comment]
Alright thanks. I think also the cubature methods were not good for my problem, so it was more problem related than solver related. Sorry about that.
